import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, BriefcaseBusiness, Languages, MapPin, Star } from "lucide-react";
import { QuoteForm } from "@/components/forms/QuoteForm";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { getServiceProviders } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
type Props = { params: { slug: string } };
export async function generateStaticParams() { return (await getServiceProviders()).map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const provider = (await getServiceProviders()).find((item) => item.slug === params.slug); return createMetadata({ title: provider?.name || "Service Provider", description: provider?.description || "Verified BhoomiKonnect service provider.", path: `/service-providers/${params.slug}`, image: provider?.image }); }
export default async function ProviderPage({ params }: Props) { const provider = (await getServiceProviders()).find((item) => item.slug === params.slug); if (!provider) notFound(); return <><section className="border-b bg-muted/50 py-8"><div className="container"><p className="text-sm text-muted-foreground"><Link href="/">Home</Link> / <Link href="/service-providers">Providers</Link> / {provider.name}</p></div></section><section className="py-10"><div className="container grid gap-8 lg:grid-cols-[1fr_380px]"><div className="space-y-6"><Card className="p-5"><div className="flex flex-col gap-5 sm:flex-row"><div className="relative size-32 shrink-0 overflow-hidden rounded-md"><Image src={provider.image} alt={`${provider.name} profile`} fill priority className="object-cover" /></div><div><Badge variant="secondary"><BadgeCheck className="size-3" aria-hidden /> Verified professional</Badge><h1 className="mt-3 text-3xl font-bold">{provider.name}</h1><p className="mt-1 text-muted-foreground">{provider.providerType} · {provider.companyName}</p><div className="mt-4 flex flex-wrap gap-2"><Badge variant="outline"><Star className="size-3 fill-accent text-accent" aria-hidden />{provider.rating.toFixed(1)} ({provider.reviewCount})</Badge><Badge variant="outline"><MapPin className="size-3" aria-hidden />{provider.city}</Badge><Badge variant="outline">{provider.experience} years</Badge></div></div></div><p className="mt-5 leading-7 text-muted-foreground">{provider.description}</p></Card><div className="grid gap-4 sm:grid-cols-3"><Card className="p-4"><BriefcaseBusiness className="size-5 text-primary" aria-hidden /><p className="mt-3 text-2xl font-bold">{provider.completedJobs}+</p><p className="text-xs text-muted-foreground">Completed jobs</p></Card><Card className="p-4"><Languages className="size-5 text-primary" aria-hidden /><p className="mt-3 font-bold">{provider.languages.join(", ")}</p><p className="text-xs text-muted-foreground">Languages</p></Card><Card className="p-4"><BadgeCheck className="size-5 text-secondary" aria-hidden /><p className="mt-3 font-bold">{provider.availability}</p><p className="text-xs text-muted-foreground">Availability</p></Card></div><Card className="p-5"><h2 className="text-2xl font-bold">Services and skills</h2><div className="mt-5 flex flex-wrap gap-2">{[...provider.services, ...provider.skills].map((item) => <Badge key={item} variant="muted">{item}</Badge>)}</div></Card></div><aside className="lg:sticky lg:top-24 lg:self-start"><QuoteForm title={`Contact ${provider.name}`} leadType="Service Booking" source="Provider Profile" providerSlug={provider.slug} compact /></aside></div></section></>; }
