import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { SectionHeading } from "@/components/sections/SectionHeading";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { getCurrentWorks } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
export const metadata: Metadata = createMetadata({ title: "Current and Completed Works", description: "Follow original demo construction, interiors, painting, and renovation work through transparent project progress.", path: "/current-works" });
export default async function CurrentWorksPage() { const works = await getCurrentWorks(); return <><section className="border-b bg-muted/50 py-10 sm:py-14"><div className="container"><SectionHeading eyebrow="Current works" title="See the work, stage by stage." description="Progress-led project pages create an accountable record of ongoing and completed construction, interior, painting, and renovation delivery." /></div></section><section className="py-10 sm:py-14"><div className="container"><div className="mb-6 flex flex-wrap gap-2">{["All", "Ongoing", "Completed", "Construction", "Interiors", "Painting", "Renovation"].map((item) => <Badge key={item} variant={item === "All" ? "default" : "outline"}>{item}</Badge>)}</div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{works.map((work) => <Card key={work.id} className="group overflow-hidden"><div className="relative aspect-[16/10] overflow-hidden"><Image src={work.image} alt={`${work.title} progress`} fill className="object-cover transition duration-500 group-hover:scale-105" /><Badge variant={work.status === "Completed" ? "secondary" : "accent"} className="absolute left-3 top-3">{work.status}</Badge></div><div className="p-5"><p className="text-xs font-bold uppercase text-primary">{work.category}</p><Link href={`/current-works/${work.slug}`} className="mt-2 block text-lg font-bold hover:text-primary">{work.title}</Link><p className="mt-2 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4" aria-hidden />{work.location}</p><div className="mt-4 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-secondary" style={{ width: `${work.progress}%` }} /></div><div className="mt-2 flex justify-between text-xs"><span>{work.progress}% complete</span><Link href={`/current-works/${work.slug}`} className="font-semibold text-primary">View progress <ArrowRight className="inline size-3" aria-hidden /></Link></div></div></Card>)}</div></div></section></>; }
