import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarDays, CheckCircle2, MapPin } from "lucide-react";
import { QuoteForm } from "@/components/forms/QuoteForm";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { getCurrentWorks } from "@/lib/content";
import { createMetadata } from "@/lib/seo";
type Props = { params: { slug: string } };
export async function generateStaticParams() { return (await getCurrentWorks()).map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const work = (await getCurrentWorks()).find((item) => item.slug === params.slug); return createMetadata({ title: work?.title || "Current Work", description: work?.description || "BhoomiKonnect project progress.", path: `/current-works/${params.slug}`, image: work?.image }); }
export default async function WorkPage({ params }: Props) { const work = (await getCurrentWorks()).find((item) => item.slug === params.slug); if (!work) notFound(); return <><section className="border-b bg-muted/50 py-8"><div className="container"><p className="text-sm text-muted-foreground"><Link href="/">Home</Link> / <Link href="/current-works">Current Works</Link> / {work.title}</p><Badge className="mt-5" variant={work.status === "Completed" ? "secondary" : "accent"}>{work.status}</Badge><h1 className="mt-4 text-4xl font-bold sm:text-5xl">{work.title}</h1><p className="mt-3 flex items-center gap-2 text-muted-foreground"><MapPin className="size-4" aria-hidden />{work.location}</p></div></section><section className="py-10"><div className="container grid gap-8 lg:grid-cols-[1fr_380px]"><div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2">{work.gallery.map((image, index) => <div key={`${image}-${index}`} className={`relative overflow-hidden rounded-lg ${index === 0 ? "aspect-[16/9] sm:col-span-2" : "aspect-[4/3]"}`}><Image src={image} alt={`${work.title} progress ${index + 1}`} fill className="object-cover" /></div>)}</div><Card className="p-5"><h2 className="text-2xl font-bold">Project progress</h2><p className="mt-3 leading-7 text-muted-foreground">{work.description}</p><div className="mt-6 h-3 rounded-full bg-muted"><div className="h-3 rounded-full bg-secondary" style={{ width: `${work.progress}%` }} /></div><p className="mt-2 text-sm font-semibold">{work.progress}% complete</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><p className="flex items-center gap-2 rounded-md bg-muted p-3 text-sm"><CalendarDays className="size-4 text-primary" aria-hidden />Started {work.startDate}</p><p className="flex items-center gap-2 rounded-md bg-muted p-3 text-sm"><CheckCircle2 className="size-4 text-secondary" aria-hidden />Target {work.expectedCompletion}</p></div></Card></div><aside className="lg:sticky lg:top-24 lg:self-start"><QuoteForm title="Start a similar project" leadType={work.category === "Interiors" ? "Interior Enquiry" : work.category === "Painting" ? "Painting Enquiry" : work.category === "Renovation" ? "Renovation Enquiry" : "Construction Quote"} source="Current Work Detail" compact /></aside></div></section></>; }
