import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, FileText, HardHat, Heart, MessageSquare, Paintbrush, PackageOpen } from "lucide-react";
import { DashboardShell } from "@/components/dashboards/DashboardShell";
import { Card } from "@/components/ui/card";
import { createMetadata } from "@/lib/seo";
import { createClient } from "@/lib/supabase/server";
export const metadata: Metadata = createMetadata({ title: "My Dashboard", description: "Manage BhoomiKonnect activity.", path: "/dashboard", noIndex: true });
export default async function DashboardPage() { const supabase = createClient(); const { data: { user } } = await supabase?.auth.getUser() || { data: { user: null } }; const roles = [{ title: "Customer", href: "/dashboard/customer", icon: Heart, copy: "Saved properties, comparisons, enquiries, visits, bookings, and quotations." }, { title: "Developer", href: "/dashboard/developer", icon: Building2, copy: "Projects, properties, leads, visits, and marketplace performance." }, { title: "Property Owner", href: "/dashboard/property-owner", icon: FileText, copy: "Submitted properties, review status, publication, and enquiries." }, { title: "Service Provider", href: "/dashboard/service-provider", icon: Paintbrush, copy: "Profile, services, portfolio, bookings, availability, and reviews." }, { title: "Contractor", href: "/dashboard/contractor", icon: HardHat, copy: "Construction enquiries, quotations, project progress, and media updates." }, { title: "Supplier", href: "/dashboard/supplier", icon: PackageOpen, copy: "Materials, quotation requests, fulfilment areas, and availability." }]; return <DashboardShell title={`Welcome${user?.user_metadata?.full_name ? `, ${user.user_metadata.full_name}` : ""}`} description="This protected workspace is ready for role-specific data from Supabase. The cards below expose the future-safe modules already represented in the database."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <Link key={role.href} href={role.href}><Card className="h-full p-5 transition hover:-translate-y-1 hover:shadow-lift"><role.icon className="size-6 text-primary" aria-hidden /><h2 className="mt-4 text-lg font-bold">{role.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{role.copy}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Open workspace <ArrowRight className="size-4" aria-hidden /></span></Card></Link>)}</div><Card className="mt-6 p-5"><h2 className="flex items-center gap-2 font-bold"><MessageSquare className="size-5 text-primary" aria-hidden />Recent activity</h2><p className="mt-3 text-sm text-muted-foreground">Enquiries and bookings will appear here after Supabase is connected and the account has activity.</p></Card></DashboardShell>; }
