import type { Metadata } from "next";
import { QuoteForm } from "@/components/forms/QuoteForm";
import { SectionHeading } from "@/components/sections/SectionHeading";
import { MaterialCard } from "@/components/services/MaterialCard";
import { getMaterials } from "@/lib/content";
import { createMetadata } from "@/lib/seo";

export const metadata: Metadata = createMetadata({ title: "Construction Materials Supply", description: "Request comparable quotations for cement, steel, sand, bricks, tiles, paints, electrical, plumbing, wood, and waterproofing materials.", path: "/materials", keywords: ["construction materials", "cement quote", "steel supplier", "building materials"] });
export default async function MaterialsPage() { const materials = await getMaterials(); return <><section className="border-b bg-muted/50 py-10 sm:py-14"><div className="container"><SectionHeading eyebrow="Materials supply" title="Source the right material with a quote, not a checkout guess." description="Share your quantity and delivery location. BhoomiKonnect routes the requirement to screened regional suppliers for comparable quotations." /></div></section><section className="py-10 sm:py-14"><div className="container"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{materials.map((material) => <MaterialCard key={material.id} material={material} />)}</div></div></section><section className="border-t bg-muted/45 py-10"><div className="container grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading eyebrow="Bulk requirement" title="Request a material quotation." description="Include brand preference, unit, quantity, delivery location, and required date. Direct checkout is intentionally deferred until supply and fulfilment operations are established." /><QuoteForm title="Material supply quote" leadType="Material Quote" source="Materials Hub" /></div></section></>; }
